version: "3.9"

services:
  db:
    image: postgres:17
    container_name: todo_postgres
    env_file:
      - .env.production
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - todo_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    build: .
    command: migrate -path ./migrations -database "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable" up
    depends_on:
       db:
          condition: service_healthy
    networks:
      - todo_net
    restart: on-failure

  my_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_app
    depends_on:
      - migrate
    env_file:
      - .env.production
    ports:
      - "9999:9999"
    networks:
      - todo_net


networks:
  todo_net:

volumes:
  pgdata: